### PR TITLE
Delete button functionality

### PR DESCRIPTION
**Pull request by ColeNelson806**
## Describe Your Changes
Added the functionality for the rule "Delete" button.
Added test to check if the "Delete" button is created.
Added test to check if the "Delete" text is rendered on the screen.
Added test to check if the "Delete" button is clicked, then the method is called.
Added test to check if when creating parent components, and adding rules, the "Delete" button is clicked, it deleted the correct rule and resets the priority.

## Type of Change
Please delete options that are not relevant.
- [ ] New feature (change that adds functionality)

## Checklist (DOD)
- [x] The code is written and passes all Acceptance criteria's
- [ ] Any Zombie code is removed
- [x] Code has proper comment documentation
- [x] The code is unit tested with happy case and passes
- [x] Code is refactored for optimization
- [ ] The code has been peer-reviewed by one or more team members who did not work on it.
- [ ] The code has no merge conflicts

### If Applicable Checklist
- [x] The code is integration tested and passes (if applicable)

### CODE REVIEW

**Review by GivenTeacher5 — COMMENTED** [review]
everything works as intended
only change i could think of is changing the name for test in create-ruleset component

**Review by rodaserg0208 — CHANGES_REQUESTED** [review]
All of the Tests look good, only thing is the priority showing. Other then that it looks good!

**Review by sophialhales — APPROVED** [review]
Looks good to me!

**Review by Scott-Code-19 — APPROVED** [review]
With the most recent fix of the Post endpoint, Everything is working as intended and is good to go.

**Pull request merged**
