### PR TITLE
Angular inside spring

### PR DESCRIPTION
**Pull request by ColeNelson806**
## Describe Your Changes
Removed React from the application.
Added Angular to the application in place of React.
Edited pom.xml file to adjust for using Angular instead of React.

## Type of Change
Please delete options that are not relevant.

- [x] Change requires a documentation update

## Checklist (DOD)
- [ ] The code is written and passes all Acceptance criteria's
- [ ] Any Zombie code is removed
- [ ] Code has proper comment documentation
- [ ] The code is unit tested with happy case and passes
- [ ] Code is refactored for optimization
- [ ] The code has been peer-reviewed by one or more team members who did not work on it.
- [ ] The code has no merge conflicts

### If Applicable Checklist
- [ ] The code is integration tested and passes (if applicable)
- [ ] The code is regression tested and passes (if applicable)
- [ ] Code is reviewed and accepted by Product Owner (if applicable)

### CODE REVIEW

**Review by sophialhales — CHANGES_REQUESTED** [review]
- Highlight or underline switching between front-end and main in the README
- Change i. and ii. language to be more clear it is one or the other (or remove one) in the README

**Comment by ColeNelson806** [comment]
> * Highlight or underline switching between front-end and main in the README
> 
>     * Change i. and ii. language to be more clear it is one or the other (or remove one) in the README

I have bolded the parts mentioning to change the directory, and I also have removed that 2nd option because after some more thought it would not be relevant later on.

**Review by sophialhales — APPROVED** [review]
looks good!

**Review by Scott-Code-19 — COMMENTED** [review]
Seems good,I also noticed the two things brought up by Sophia which have since been updated.

**Pull request merged**
